baseURL = 'https://galfudim.dev/'
languageCode = 'en-us'
title = 'Gal Fudim'
theme = 'blowfish'

[params]
    description = 'Personal website and blog'
    colorScheme = 'ocean'
    defaultAppearance = 'dark'
    autoSwitchAppearance = true
    copyright = 'Â© 2025 galfudim.dev'
    disableTextInHeader = true
    
    [params.footer]
    showThemeAttribution = true

    [params.homepage]
    layout = 'profile'
    showRecent = false

    [params.author]
    name = "Gal Fudim"
    headline = "Software engineer"
    image = "avatar.png"

[menu]
    [[menu.main]]
        name = 'home'
        url = '/'
        weight = 10
    [[menu.main]]
        name = 'blog'
        url = '/blog/'
        weight = 20
    [[menu.main]]
        name = 'about'
        url = '/about/'
        weight = 30
    [[menu.main]]
        identifier = "github"
        pre = "github"
        url = "https://github.com/galfudim"
        weight = 40
    [[menu.main]]
        identifier = "linkedin"
        pre = "linkedin"
        url = "https://linkedin.com/in/galfudim"
        weight = 50